import type { ChapterMeta } from '../../src/content/types'

export function renderIndex(metas: ChapterMeta[]): string {
  // JSON modules infer `type: string`, so each import is cast to the ChapterDoc contract.
  const loaders = metas
    .map(
      (m) =>
        `  '${m.id}': () => import('./chapters/${m.id}.json') as Promise<{ default: ChapterDoc }>,`,
    )
    .join('\n')
  return [
    '// GENERATED by scripts/extract-book.ts. Do not edit; re-run `npm run extract -- <epub>`.',
    `import type { ChapterDoc, ChapterMeta } from './types'`,
    '',
    `export const chapterIndex: ChapterMeta[] = ${JSON.stringify(metas, null, 2)}`,
    '',
    'export const chapterLoaders: Record<string, () => Promise<{ default: ChapterDoc }>> = {',
    loaders,
    '}',
    '',
  ].join('\n')
}
