// @vitest-environment node
import { describe, expect, it } from 'vitest'
import { renderIndex } from '../lib/write-index'

describe('renderIndex', () => {
  it('emits typed metadata and lazy loaders per chapter', () => {
    const src = renderIndex([
      { id: '0', number: 0, title: 'Quick Tricks', kicker: 'Chapter 0', sections: [{ id: 'overview', title: 'Overview' }] },
      { id: 'epilogue', number: null, title: 'Epilogue', kicker: 'Chapter ∞', sections: [] },
    ])
    expect(src).toContain('// GENERATED by scripts/extract-book.ts')
    expect(src).toContain(`import type { ChapterDoc, ChapterMeta } from './types'`)
    expect(src).toContain(`export const chapterIndex: ChapterMeta[] = [`)
    expect(src).toContain(`"id": "0"`)
    expect(src).toContain(`'0': () => import('./chapters/0.json')`)
    expect(src).toContain(`'epilogue': () => import('./chapters/epilogue.json')`)
    expect(src).toContain('export const chapterLoaders: Record<string, () => Promise<{ default: ChapterDoc }>>')
  })
})
